### PR TITLE
[config][testdata] remove hipchat from global config

### PR DESCRIPTION
**Pull request by CH-AishaLugg**
[AlertConfig is a service that scrapes Collective Health repos looking for alerting based configs](https://collectivehealth.atlassian.net/wiki/spaces/ENG/pages/12784338658/AlertConfig). This is a config file for alertmanager that contain `https://api.hipchat.com/` in the global config. We need to remove the lines containing hipchat since its the cause of errors when reloading alertmanager config. 

When reloading alertmanager configurations with curl --request POST http://monitoringserver001prod.auw2.i.cchh.io:9093/-/reload,  the output of this is 

```
failed to reload config: yaml: unmarshal errors:
  line 11: field hipchat_api_url not found in type config.plain
```

After removing the lines of code , run the steps [here ](https://github.com/collectivehealth/runbooks/blob/master/alertconfig/README.md#activating-a-new-config)

ticket : https://collectivehealth.atlassian.net/browse/SIP-240

### CODE REVIEW

**Comment by CH-AishaLugg** [comment]
the line that contain https://api.hipchat.com/ is in global config and this is whats cause the error.
hipchat is not needed/unused. -reason why most of the lines were removed  but also has relations to the config of hipchat (which does not work :grimacing:)

**Review by CH-JamielAlmeida — CHANGES_REQUESTED** [review]
This is removing the part of the code that parses hipchat configuration from the yaml config. This is not what we want to do.

**Review by CH-HaroldShort — COMMENTED** [review]
It's a good start, though I'll advocate for removing the rest of the Hipchat references as well:
https://github.com/search?q=repo%3Acollectivehealth%2Falertmanager%20Hipchat&type=code

**Comment by CH-HaroldShort** [comment]
May I suggest another PR doing the same for WeChat

**Comment by CH-AishaLugg** [comment]
@CH-HaroldShort I'm going to close this PR. confd is retrieving data from etcd where this config is stored as a value.

**Pull request closed without merging**
